POST http://localhost:8080/facade
Content-Type: application/json

"Hello, World!"
###

POST http://localhost:8080/facade
Content-Type: application/json

"Hello, World 1!"
###

GET http://localhost:8080/facade
Accept: text/html
###

POST http://localhost:8080/facade
Content-Type: application/json

"Hello, World 2!"
###


GET http://localhost:8080/facade
Accept: text/html
###